# Thats only we need for making test in individual db. Don't forget --test key for doctrine commands!
#
#
# php app/console doctrine:fixtures:load --fixtures=src/Ens/JobeetBundle/Tests/DataFixtures/ORM/ --env=test
# to load test fixtures
#

imports:
    - { resource: config.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
doctrine:
     dbal:
         host: localhost
         dbname: testdb
         user: root
         password: 123456
